[package]
name = "process_c2rust"
version = "0.0.0"
edition = "2018"
license = "MIT"

[[bin]]
name = "process_c2rust"
path = "src/main.rs"

[dependencies]
syn = { version = "1", features = ["full", "visit-mut"] }
